[package]
name = "tiny-transport-bin"
version = "0.1.0"
authors = ["Jakob Stigloher <pixunil@posteo.eu>"]
edition = "2018"
description = "Provides a command line interface"
repository = "https://github.com/pixunil/tiny-transport"
license = "MIT"

[dependencies]
bincode = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = "~2.33.0"
dirs = "3.0.1"
itertools = "0.9"
rustyline = "6.2.0"
shlex = "0.1.1"
zip = { version = "0.5", default-features = false, features = ["bzip2"] }

import = { package = "tiny-transport-import", path = "../import", features = ["progress"] }
storage = { package = "tiny-transport-storage", path = "../storage" }
simulation = { package = "tiny-transport-simulation", path = "../simulation" }
