[package]
name = "gtfs-sim-bin"
version = "0.1.0"
authors = ["Jakob Stigloher <pixunil@posteo.eu>"]
edition = "2018"
description = "Provides a command line interface"
repository = "https://github.com/pixunil/gtfs-sim"
license = "MIT"

[dependencies]
bincode = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = "~2.33.0"
itertools = "0.8"
zip = { version = "0.5", default-features = false, features = ["bzip2"] }

import = { package = "gtfs-sim-import", path = "../import", features = ["progress"] }
serialization = { package = "gtfs-sim-serialization", path = "../serialization" }
simulation = { package = "gtfs-sim-simulation", path = "../simulation" }
