language: rust

cache:
  directories:
    - /home/travis/.cargo

git:
  lfs_skip_smudge: true

os: linux

script:
  - cargo build --workspace
  - cargo test --workspace --exclude gtfs-sim-bin

jobs:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - name: Linting
      before_script:
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - cargo clippy
        - cargo clippy --tests
        - cargo fmt --all -- --check
    - name: Coverage
      script:
        - docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin sh -c "cargo tarpaulin" &&
          bash <(curl -s https://codecov.io/bash)
    - name: Build
      install:
        - cargo install wasm-pack
      before_script:
        - git lfs pull
      script:
        - cargo run --release import import/data/vbb.bzip
        - cargo run --release load
        - wasm-pack build wasm --target web --out-dir www/wasm
      before_deploy:
        - rm wasm/www/wasm/.gitignore
      deploy:
        provider: pages:git
        edge: true
        token: $GITHUB_TOKEN
        local_dir: wasm/www
  allow_failures:
    - rust: nightly
