language: rust
sudo: required

cache:
  directories:
    - /home/travis/.cargo

git:
  lfs_skip_smudge: true

os: linux

addons:
  apt:
    packages:
      - libssl-dev

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --all
  - cargo test --all

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin --force &&
    cargo tarpaulin --all --ignore-tests --out Xml &&
    bash <(curl -s https://codecov.io/bash)
  fi

jobs:
  include:
    - stage: build
      install:
        - cargo install --force wasm-pack
      before_script:
        - git lfs pull
      script:
        - cargo run --package gtfs-sim-import --release import import/data/vbb.bzip
        - wasm-pack build wasm --target web --out-dir www/wasm
      after_success:
        - echo "Skipped coverage reporting"
      before_deploy:
        - rm wasm/www/wasm/.gitignore
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: wasm/www
  allow_failures:
    - rust: nightly

stages:
  - test
  - build
