language: rust

cache:
  directories:
    - /home/travis/.cargo

git:
  lfs_skip_smudge: true

os: linux

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --all
  - cargo test --all

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin sh -c "cargo tarpaulin --ignore-tests --out Xml" &&
    bash <(curl -s https://codecov.io/bash)
  fi

jobs:
  include:
    - stage: build
      install:
        - cargo install wasm-pack
      before_script:
        - git lfs pull
      script:
        - cargo run --release import import/data/vbb.bzip
        - cargo run --release load
        - wasm-pack build wasm --target web --out-dir www/wasm
      after_success:
        - echo "Skipped coverage reporting"
      before_deploy:
        - rm wasm/www/wasm/.gitignore
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: wasm/www
  allow_failures:
    - rust: nightly

stages:
  - test
  - build
