[package]
name = "gtfs-sim-storage"
version = "0.1.0"
authors = ["Jakob Stigloher <pixunil@posteo.eu>"]
edition = "2018"
description = "Stores simulation data space-efficient"
repository = "https://github.com/pixunil/gtfs-sim"
license = "MIT"

[features]
fixtures = []

[dependencies]
itertools = "0.8"
serde = "1"
serde_derive = "1"
na = { package = "nalgebra", version = "0.18.0", features = ["serde-serialize"] }

simulation = { package = "gtfs-sim-simulation", path = "../simulation", features = ["fixtures"] }

[dev-dependencies]
test_utils = { package = "gtfs-sim-test", path = "../test" }
