[package]
name = "tiny-transport-common"
version = "0.1.0"
authors = ["Jakob Stigloher <pixunil@posteo.eu>"]
edition = "2018"
description = "Provides common utilities"
repository = "https://github.com/pixunil/tiny-transport"
license = "MIT"
